import os

project_name = input("Enter project name: ")
cmake_version = input("Enter CMake minimum required version (default 4.1.2): ")
if not cmake_version:
    cmake_version = "4.1.2"
cpp_version = input("Enter C++ standard version (default 23): ")
if not cpp_version:
    cpp_version = "23"

if not os.path.exists("bin"):
    os.makedirs("bin")

with open("bin/" + project_name + "_CMakeLists.txt", "w") as f:
    f.write("# Setup CMake project\n")
    f.write("cmake_minimum_required(VERSION " + cmake_version + ")\n")
    f.write("project(" + project_name + ")\n\n")
    f.write("set(CMAKE_CXX_STANDARD " + cpp_version + ")\n\n")
    f.write("# Source files\n")
    f.write("file(GLOB_RECURSE GAME_SOURCES \n")
    f.write("\t\"${CMAKE_CURRENT_SOURCE_DIR}/source/*.cpp\" # Edit game source path as needed\n")
    f.write(")\n\n")
    f.write("# Executable\n")
    f.write("if(CMAKE_BUILD_TYPE STREQUAL \"Debug\")\n")
    f.write("\tadd_executable(" + project_name + " \n")
    f.write("\t\t${GAME_SOURCES}\n")
    f.write("\t)\n")
    f.write("elseif(CMAKE_BUILD_TYPE STREQUAL \"Release\")\n")
    f.write("\tif(WIN32)\n")
    f.write("\t\tadd_executable(" + project_name + " WIN32 # Hide console window\n")
    f.write("\t\t\t${GAME_SOURCES}\n")
    f.write("\t\t)\n")
    f.write("\telse()\n")
    f.write("\t\tadd_executable(" + project_name + " \n")
    f.write("\t\t\t${GAME_SOURCES}\n")
    f.write("\t\t)\n")
    f.write("\tendif()\n")
    f.write("endif()\n\n")
    f.write("# Include directories\n")
    f.write("target_include_directories(" + project_name + " PRIVATE \n")
    f.write("\t\"${CMAKE_CURRENT_SOURCE_DIR}/include\" # Edit game include path as needed\n")
    f.write("\t# (NOTE) YOU NEED TO ADD A PATH HERE TO POINT TO THE LAPENGINE INCLUDE DIRECTORY\n")
    f.write(")\n\n")
    f.write("# Library directories and linking\n")
    f.write("target_link_directories(" + project_name + " PRIVATE \n")
    f.write("\t\"${CMAKE_CURRENT_SOURCE_DIR}/lib\" # Edit library path as needed\n")
    f.write(")\n\n")
    f.write("if(WIN32)\n")
    f.write("\ttarget_link_libraries(" + project_name + " PRIVATE \n")
    f.write("\t\tlapEngine\n")
    f.write("\t\traylib\n")
    f.write("\t\twinmm\n")
    f.write("\t)\n")
    f.write("else()\n")
    f.write("\ttarget_link_libraries(" + project_name + " PRIVATE \n")
    f.write("\t\tlapEngine\n")
    f.write("\t\traylib\n")
    f.write("\t)\n")
    f.write("endif()\n")